version: 2.1
jobs:
  run_tests:
    docker:
     - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command: |
            npm install --save
      - run:
          name: Run tests
          command: npm test 
workflows:
  build_tests:
    jobs:
      - run_tests
        
